export const data = [
    {
      id: 1,
      name: "React Native",
      price: 200.0,
      newPrice: 150.0,
      url: "https://www.datocms-assets.com/45470/1631026680-logo-react-native.png",
      author: "John Doe",
      cover: "https://cdn.kinandcarta.com/-/media-assets/images/kincarta/insights/2022/02/react-native/react_hero.png?as=0&iar=0&w=1200&rev=61e1dad3af7e465e9544cf8490237772&hash=0AD31383BCBA1DA1C88546327312BA33",
      description: "Um curso abrangente sobre desenvolvimento de aplicativos móveis usando React Native.",
      about: "Neste curso, você aprenderá os conceitos fundamentais do React Native e como construir aplicativos móveis multiplataforma. O curso abrange desde os conceitos básicos até tópicos avançados, permitindo que você desenvolva aplicativos móveis de alta qualidade.",
      assessment: 4.5,
      n_assessment: 120,
    },
    {
      id: 2,
      name: "Python para Ciência de Dados",
      price: 250.0,
      newPrice: 180.0,
      url: "https://images.credly.com/size/180x180/images/84ac9eff-b8a2-4683-846b-f59887a73801/Python_101_Data_Science.png",
      author: "Maria Silva",
      cover: "https://www.example.com/python-data-science-cover",
      description: "Um curso abrangente sobre programação Python para ciência de dados.",
      about: "Neste curso, você aprenderá os fundamentos da linguagem Python e como aplicá-la em projetos de ciência de dados. Você também aprenderá sobre bibliotecas populares, como NumPy, Pandas e Matplotlib, para manipulação e visualização de dados.",
      assessment: 4.8,
      n_assessment: 95,
    },
    {
      id: 3,
      name: "Fundamentos do JavaScript",
      price: 150.0,
      newPrice: 100.0,
      url: "https://example.com/javaScript",
      author: "Carlos Santos",
      cover: "https://www.example.com/javascript-fundamentals-cover",
      description: "Um curso abrangente sobre os fundamentos da linguagem JavaScript.",
      about: "Neste curso, você aprenderá os conceitos básicos do JavaScript, incluindo sintaxe, manipulação do DOM e programação assíncrona. Você também explorará o desenvolvimento web com JavaScript e como criar interações dinâmicas em páginas da web.",
      assessment: 4.2,
      n_assessment: 80,
    },
    {
      id: 4,
      name: "Arquiteto de Soluções Certificado AWS",
      price: 300.0,
      newPrice: 250.0,
      url: "https://example.com/aws-solutions-architect",
      author: "Ana Rodrigues",
      cover: "https://www.example.com/aws-solutions-architect-cover",
      description: "Um curso completo para se tornar um arquiteto de soluções certificado pela AWS.",
      about: "Neste curso, você aprenderá a projetar e implantar soluções seguras, escaláveis e confiáveis na plataforma da Amazon Web Services. O curso abrange tópicos como computação em nuvem, armazenamento, redes, segurança e melhores práticas para arquitetura na AWS.",
      assessment: 4.6,
      n_assessment: 110,
    },
    {
      id: 5,
      name: "Estruturas de Dados e Algoritmos",
      price: 180.0,
      newPrice: 120.0,
      url: "https://example.com/data-structures-algorithms",
      author: "Rafaela Ferreira",
      cover: "https://www.example.com/data-structures-algorithms-cover",
      description: "Um curso abrangente sobre estruturas de dados e algoritmos.",
      about: "Neste curso, você aprenderá sobre as estruturas de dados mais comumente usadas, como listas, pilhas, filas, árvores e grafos. Você também explorará algoritmos clássicos, como ordenação e pesquisa, e aprenderá a analisar a eficiência dos algoritmos.",
      assessment: 4.3,
      n_assessment: 75,
    },
    {
      id: 6,
      name: "Aprendizado de Máquina com Python",
      price: 220.0,
      newPrice: 160.0,
      url: "https://example.com/machine-learning-python",
      author: "Pedro Almeida",
      cover: "https://www.example.com/machine-learning-python-cover",
      description: "Um curso abrangente sobre aprendizado de máquina usando a linguagem Python.",
      about: "Neste curso, você aprenderá os fundamentos do aprendizado de máquina, incluindo classificação, regressão, agrupamento e avaliação de modelos. Você também explorará bibliotecas populares, como Scikit-learn e TensorFlow, para criar e treinar modelos de aprendizado de máquina.",
      assessment: 4.7,
      n_assessment: 105,
    },
    {
      id: 7,
      name: "Desenvolvimento Full Stack",
      price: 280.0,
      newPrice: 200.0,
      url: "https://example.com/full-stack-web-development",
      author: "Luís Oliveira",
      cover: "https://www.example.com/full-stack-web-development-cover",
      description: "Um curso completo para se tornar um desenvolvedor full stack.",
      about: "Neste curso, você aprenderá a criar aplicativos web completos, desde a criação do front-end usando HTML, CSS e JavaScript até o desenvolvimento do back-end com frameworks populares, como Node.js e Express. Você também explorará bancos de dados, autenticação de usuários e implantação de aplicativos.",
      assessment: 4.9,
      n_assessment: 150,
    },
    {
      id: 8,
      name: "Essenciais de Segurança Cibernética",
      price: 190.0,
      newPrice: 140.0,
      url: "https://example.com/cybersecurity-essentials",
      author: "Mariana Costa",
      cover: "https://www.example.com/cybersecurity-essentials-cover",
      description: "Um curso abrangente sobre os conceitos essenciais de segurança cibernética.",
      about: "Neste curso, você aprenderá sobre os principais conceitos e princípios de segurança cibernética, incluindo criptografia, proteção de redes, gerenciamento de riscos e resposta a incidentes. Você também explorará técnicas de hacking ético para entender melhor as vulnerabilidades e como proteger sistemas e dados.",
      assessment: 4.4,
      n_assessment: 90,
    },
    {
      id: 9,
      name: "Noções Básicas de Inteligência Artificial",
      price: 240.0,
      newPrice: 170.0,
      url: "https://example.com/ai-basics",
      author: "Gustavo Fernandes",
      cover: "https://www.example.com/ai-basics-cover",
      description: "Um curso introdutório sobre os fundamentos da inteligência artificial.",
      about: "Neste curso, você aprenderá sobre os conceitos básicos da inteligência artificial, incluindo aprendizado de máquina, redes neurais e processamento de linguagem natural. Você também explorará aplicações práticas da IA em campos como visão computacional, reconhecimento de voz e sistemas de recomendação.",
      assessment: 4.1,
      n_assessment: 65,
    },
    {
      id: 10,
      name: "Desenvolvimento de Blockchain",
      price: 260.0,
      newPrice: 190.0,
      url: "https://example.com/blockchain-development",
      author: "André Santos",
      cover: "https://www.example.com/blockchain-development-cover",
      description: "Um curso abrangente sobre desenvolvimento de aplicações com tecnologia blockchain.",
      about: "Neste curso, você aprenderá os princípios do blockchain e como desenvolver aplicativos descentralizados usando frameworks e linguagens populares, como Ethereum e Solidity. Você também explorará casos de uso reais de blockchain, como contratos inteligentes e tokens digitais.",
      assessment: 4.7,
      n_assessment: 100,
    },
  ];